
apiVersion: v1
kind: Service
metadata:
  name: wso2ei-integrator-service
  namespace: "$ns.k8s&wso2.ei"
  labels:
    deployment: wso2ei-integrator
    product: wso2ei
spec:
  selector:
    deployment: wso2ei-integrator
    product: wso2ei
  type: NodePort
  ports:
    - name: servlet-http
      port: 9763
      targetPort: 9763
      protocol: TCP
    - name: servlet-https
      port: 9443
      targetPort: 9443
      protocol: TCP
      nodePort: "$nodeport.k8s.&.1.wso2ei"
---
